# Generated by Django 4.2.3 on 2023-07-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS4', 'Playstation'), ('X1', 'XBOX')], max_length=3)),
                ('discordID', models.IntegerField()),
                ('discordName', models.CharField(max_length=50)),
                ('rank', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player1', to='tournaments.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player2', to='tournaments.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player3', to='tournaments.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undefined', max_length=100)),
                ('description', models.TextField(default='undefined')),
                ('teams', models.ManyToManyField(to='tournaments.team')),
            ],
        ),
    ]
